/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fdf9f1",
        "surface-bright": "#fdf9f1",
        "background": "#fdf9f1",
        "surface-container": "#f1ede6",
        "surface-container-low": "#f7f3eb",
        "surface-container-high": "#ece8e0",
        "surface-container-highest": "#e6e2da",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e6e2da",
        "surface-dim": "#dddad2",
        "primary": "#815500",
        "primary-container": "#c68b29",
        "primary-fixed": "#ffddb2",
        "primary-fixed-dim": "#fcba55",
        "on-primary": "#ffffff",
        "on-primary-container": "#422a00",
        "on-primary-fixed": "#291800",
        "on-primary-fixed-variant": "#624000",
        "secondary": "#a43c1b",
        "secondary-dark": "#882f13",
        "secondary-container": "#fe7e57",
        "secondary-fixed": "#ffdbd1",
        "secondary-fixed-dim": "#ffb59f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6f1b00",
        "on-secondary-fixed": "#3a0a00",
        "on-secondary-fixed-variant": "#842504",
        "tertiary": "#456553",
        "tertiary-light": "#eaf2ec",
        "tertiary-container": "#7c9e89",
        "tertiary-fixed": "#c7ebd4",
        "tertiary-fixed-dim": "#abcfb8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#143525",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#2d4d3c",
        "on-surface": "#1c1c17",
        "on-surface-variant": "#504536",
        "outline": "#837564",
        "outline-soft": "#e5dcce",
        "outline-variant": "#d5c4b0",
        "gold-accent": "#d49a3d",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "gutter": "1.25rem",
      },
      fontFamily: {
        headline: ["Playfair Display", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["26px", { lineHeight: "34px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "68px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
